-- Create real_attacks table for tracking real external attacks
-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.real_attacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    attack_type VARCHAR(50) NOT NULL,
    source_ip VARCHAR(45) NOT NULL,
    target_ip VARCHAR(45) NOT NULL,
    payload JSONB DEFAULT '{}',
    status VARCHAR(20) DEFAULT 'detected',
    severity VARCHAR(20) DEFAULT 'high',
    processed BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_real_attacks_timestamp ON public.real_attacks(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_real_attacks_source_ip ON public.real_attacks(source_ip);
CREATE INDEX IF NOT EXISTS idx_real_attacks_attack_type ON public.real_attacks(attack_type);
CREATE INDEX IF NOT EXISTS idx_real_attacks_status ON public.real_attacks(status);

-- Add RLS (Row Level Security) policies
ALTER TABLE public.real_attacks ENABLE ROW LEVEL SECURITY;

-- Policy to allow all operations (for demo purposes)
CREATE POLICY "Enable all operations for real_attacks" ON public.real_attacks
    FOR ALL USING (true) WITH CHECK (true);

-- Add updated_at trigger
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER handle_real_attacks_updated_at
    BEFORE UPDATE ON public.real_attacks
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Add comments for documentation
COMMENT ON TABLE public.real_attacks IS 'Table to track real external attacks received from attacker devices';
COMMENT ON COLUMN public.real_attacks.attack_type IS 'Type of attack: ddos, bruteforce, cryptominer, insider';
COMMENT ON COLUMN public.real_attacks.source_ip IS 'IP address of the attacker device';
COMMENT ON COLUMN public.real_attacks.target_ip IS 'IP address of the target system';
COMMENT ON COLUMN public.real_attacks.payload IS 'Additional attack data and metadata';
COMMENT ON COLUMN public.real_attacks.status IS 'Attack status: detected, blocked, investigating, resolved';
COMMENT ON COLUMN public.real_attacks.severity IS 'Attack severity: low, medium, high, critical';
COMMENT ON COLUMN public.real_attacks.processed IS 'Whether the attack has been processed by the correlation engine';
